---
title: "Statistical Inference"
subtitle: "Ph.D. in Economics, Statistics, and Data Science - University of Milano-Bicocca"
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
lang: en
page-layout: full
execute:
  cache: false
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [simplex, template.css]
    toc: true
    toc-title: Table of contents
    embed-resources: false
    code-line-numbers: true
    smooth-scroll: true
    fig-dpi: 250
editor: 
  markdown: 
    wrap: 72
editor_options: 
  chunk_output_type: console
---

This is the website of the [Statistical Inference]{.blue} course of the
"*Ph.D. in Economics, Statistics, and Data Science* (Curriculum
Statistics)", Università degli Studi di Milano-Bicocca.

## Teaching material

#### Textbooks 

- Agresti, A. 2013. [*Categorical Data Analysis*](https://onlinelibrary.wiley.com/doi/book/10.1002/0471249688). Third Edition. Wiley.
- Casella, G., and R. L. Berger. 2002. [*Statistical Inference*](https://www.routledge.com/Statistical-Inference/Casella-Berger/p/book/9781032593036). Duxbury Advanced Series. Duxbury.
- Davison, A. C. 2003. [*Statistical Models*](https://www.cambridge.org/core/books/statistical-models/8EC19F80551F52D4C58FAA2022048FC7). Cambridge University Press.
- Lehmann, E. L., and G. Casella. 1998. [*Theory of Point Estimation*](https://link.springer.com/book/10.1007/b98854). Springer.
<!-- - Efron, B. 2023. [*Exponential Families in Theory and Practice*](https://www.cambridge.org/core/books/exponential-families-in-theory-and-practice/45CE4C98DEAB5EC9D6934E9DAC002F5F). Cambridge University Press. -->
- McCullagh, P., and J. A. Nelder. 1986. [*Generalized Linear Models*](https://www.taylorfrancis.com/books/mono/10.1201/9780203753736/generalized-linear-models-mccullagh). Chapman & Hall/CRC.
- Pace, L., and A. Salvan. 1997. [*Principles of Statistical Inference from a Neo-Fisherian Perspective*](https://www.worldscientific.com/worldscibooks/10.1142/3409). Advanced Series on Statistical Science and Applied Probability. World Scientific.
- van der Vaart, A. W. 1998. [*Asymptotic Statistics*](https://www.cambridge.org/core/books/asymptotic-statistics/A3C7DAD3F7E66A1FA60E9C8FE132EE1D). Cambridge University Press.

### Slides and lecture notes

The slides are meant to be used in HTML. However, if you *really* want
to convert the HTML slides into pdf files, you can [follow the
instruction of the quarto
documentation](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf).

| Topic                           | Notes                                | Slides                                             | Code                  |
|--------------------|------------------|------------------|------------------|
| **Introduction**                | [Introduction](slides/un_intro.html) | [Slides Introduction](slides/un_intro_slides.html) |                       |
| **Point estimation**            | [Unit A](slides/un_A.html)           | [Slides Unit A](slides/un_A_slides.html)           | [Code A](code/un_A.R) |
| *Exercises*                     | [Exercises A](exe/exe_A.html)        |                                                    |                       |
| **Exponential families**        | [Unit B](slides/un_B.html)           | [Slides Unit B](slides/un_B_slides.html)           | [Code B](code/un_B.R) |
| *Exercises*                     | [Exercises B](exe/exe_B.html)        |                                                    |                       |
| **Generalized linear models**   | [Unit C](slides/un_C.html)           | [Slides Unit C](slides/un_C_slides.html)           | [Code C](code/un_C.R) |
| *Exercises*                     | [Exercises C](exe/exe_C.html)        |                                                    |                       |
| **Advanced statistical models** | [Unit D](slides/un_D.html)           | [Slides Unit D](slides/un_D_slides.html)           | [Code D](code/un_D.R) |
| *Exercises*                     | [Exercises D](exe/exe_D.html)        |                                                    |                       |

<!-- ## Exam -->

<!-- #### Mock exam -->

<!-- An example of written examination is provided at [this link](exe/exe_exam.html).  -->

<!-- ## Prerequisites -->

<!-- Knowledge of the topics (i) linear algebra, (ii) linear models is highly recommended. -->

<!-- Knowledge of topics covered in the courses Probability and Statistics M -->

<!-- and Advanced Statistics M is also highly recommended. -->

## Acknowledgments

<!-- The primary source of this website's content are the textbooks [Azzalini and Scarpa (2011)]{.blue} and [Hastie, Tibshirani, and Friedman (2009)]{.orange}. A few pictures have been taken from the textbooks; in these cases the original source is cited.  -->

I have made use of several other books, scientific articles, and
datasets to complement the main textbooks. They are all cited at the end
of each unit. Students are encouraged to consult the books: these slides
are just a concise summary.

<!-- I am also grateful to Aldo Solari, who gracefully shared the material of the courses [Data Mining](https://aldosolari.github.io/DM/) and [Statistical Learning](https://aldosolari.github.io/SL/). These websites have been used to lay the basis of this course. -->

All the mistakes still present are mine.

------------------------------------------------------------------------
